apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ... # Certificate of the cluster, this will different for each individual
    server: http://kubernetes.docker.internal:6443       # Cluster url
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate: ...    # Client cert to authority with Kubernetes
    client-key: ...            # Client key to authority with Kubernetes
