apiVersion: v1
kind: Service
metadata:
  name: dummy
  labels:
    app: demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 1500
      targetPort: 1500
      nodePort: 30000
